name: Deploy Angular

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh sebastian@127.0.0.1 << 'EOF'
          # Stop existing Angular container
          docker stop angular || true && docker rm angular || true

          # Pull latest Angular code
          cd /home/sebastian/e-commerce/angular
          git pull origin main

          # Build and run Angular container
          docker build -t angular-frontend .
          docker run -d --name angular -p 80:80 angular-frontend
        EOF
